//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.22 at 10:46:37 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.forum-datenaustausch.ch/invoice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.metas.vertical.healthcare_ch.forum_datenaustausch_ch.invoice_450.response;
