<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ #%L
  ~ model
  ~ %%
  ~ Copyright (C) 2022 Adekia
  ~ %%
    
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.adekia.exchange</groupId>
        <artifactId>com-adekia-exchange</artifactId>
        <version>10.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <groupId>com.adekia.exchange</groupId>
    <artifactId>exchange-model</artifactId>
    <name>Adekia Exchange - models (UBL)</name>
    <packaging>jar</packaging>
    <version>10.0.0</version>
    <url>https://www.adekia.com</url>

    <dependencies>
        <dependency>
            <groupId>com.helger.ubl</groupId>
            <artifactId>ph-ubl23</artifactId>
            <version>6.7.0</version>
        </dependency>
    </dependencies>





</project>