//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.22 at 10:32:39 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://erpel.at/schemas/1p0/messaging/header", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package at.erpel.schemas._1p0.messaging.header;
